### ISSUE TITLE
Lockout date after X orders field is not working properly.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/woocommerce-delivery-date#74]
Here i set Lockout date after X orders as 6.Now i placed the order for the first time 3 qty and the second time 4 qty for the same delivery date then an order is placed which is wrong.

Screenshot of Order received page for 3 qty: https://www.screencast.com/t/j9Cdf89Lhym
Screenshot of Order received page for 4 qty: https://www.screencast.com/t/ox82uib4y
Screenshot of setting page: https://www.screencast.com/t/gebBgXf9d

**Comment by komal-maru** [comment]
We do not have the feature where the delivery date will be booked based on the quantities in the Lite version. In Lite version, the lockout only works with the number of orders placed and not with quantities.

The above feature is only available in the Pro version.

Hence the issue is marked as Invalid and closing it.

**Comment by ashokrane** [comment]
Nothing to test here.
